//////////////////////////////////////////////////////////////////////
//
//	2167A Global External Variables
//	
//
//	This file defines all the global externals variables necessary to 
//	support all the 2167A documents defined by IDE (i.e. SRS, IRS, SDD
//	and IDD).  This file only contains boiler plate values.
//
//////////////////////////////////////////////////////////////////////


external string contract_number = "<CONTRACT NUMBER>";
external_help = "The project contract number";

external string cdrl_number = "<CDRL NUMBER>";
external_help = "the Contract Data Requirements List Sequence Number";

external string contracting_agency_and_dept_code = 
	"<CONTRACTING AGENCY AND DEPT CODE>";
external_help = "Name and department code of the contracting agency";

external string contractor_name_and_address = 
	"<CONTRACTOR NAME AND ADDRESS>";
external_help = "The name and address of the contractor";

external string system_name = "<SYSTEM NAME>";
external_help = "The title/name of system to which the document applies";

external string system_abbreviation = "";
external_help = "the abbreviation for the system title, if applicable";

external string system_number = "<SYSTEM NUMBER>";
external_help = "The identifying number for the system";

 
