//
// 	StP/IM
// 	Confidential property of Interactive Development Environments, Inc.
// 	Copyright (c) 1996
// 	All rights reserved
//

//
//	FILE:	2167A_formats.inc
//
const string DefaultFormatFile = "2167A";

const string FigureFormat = "Figure";
const string TableTitleFormat = "TableTitle";
const string TableHeaderCellFormat = "TableHeaderCell";
const string TableBodyCellFormat = "TableBodyCell";
const string TitleDocInfoFormat = "TitleDocInfo";
const string TitleMainFormat = "TitleMain";
const string TitlePrepInfoFormat = "TitlePrepInfo";
const string TitleSignaturesFormat = "TitleSignatures";
const string HeadingL1Format = "Heading 1";
const string HeadingL2Format = "Heading 2";
const string HeadingL3Format = "Heading 3";
const string HeadingL4Format = "Heading 4";
const string HeadingLFormat = "Heading ";
const string SubSectionBodyFormat = "SubSectionBody";
const string SubSectionListFormat = "SubSectionList";
const string SubSectionTitleFormat = "SubSectionTitle";
const string AppendixL1StartFormat = "Appendix L1 Start";
const string AppendixL1Format = "Appendix L1";
const string AppendixL2Format = "Appendix L2";
const string AlphaListStartFormat = "AlphaListStart";
const string AlphaListFormat = "AlphaList";
const string IndentBody1Format = "IndentBody1";
const string SectionFormat = "Section";
const string FlowsFormat = "Flows";

