//*****************************************************************************
// DESCRIPTION: UML_Include_E.inc
//              ----------------------
//              (c) 1997 by AONIX GmbH
//*****************************************************************************
//
// Include Statements for all included files needed for the english UML-Report. 
// This is the only file included in the UML_Report_E wrapper and allows us
// to change our include strategy in future versions of the report
//*****************************************************************************
// Included Files:
// 
// UML_Include.inc :     Includes all other files, needed for UML_Report
// UML_Externals_E.inc : Includes english externals + mapping for UML_Report_E
//*****************************************************************************
#include "qrl/include/UML_Include.inc"
#include "qrl/include/UML_Externals_E.inc"

