//
// 	sccsid[] = %W% %Y% %D%
// 	StP/IM
// 	Confidential property of Interactive Development Environments, Inc.
// 	Copyright (c) 1996
// 	All rights reserved
//

//
//	FILE:	all_files_formats.inc
//
const string DefaultFormatFile = "all_files";

const string TableBodyCellFormat = "TableBodyCell";
const string TableHeaderCellFormat = "TableHeaderCell";
const string FigureTitleFormat = "FigureTitle";
const string SectionFormat = "Section";
const string SeparatorFormat = "Separator";
const string Object1Format = "Object1";
const string ObjectFormat = "Object";
const string NoteFormat = "Note";
const string ItemFormat = "Item";
const string DescriptionFormat = "Description";
const string Note1Format = "Note1";
const string Item1Format = "Item1";
const string Description1Format = "Description1";
