#include "qrl/include/se_defs.inc"

/* Symbol types */
const string PROCESS =		    	"Process";
const string OFFPAGE_PROCESS =		"OffPageProcess";
const string OFFPAGE_EXTERNAL =		"OffPageExternal";
const string DATA_STORE =		"Store";
const string EXTERNAL = 		"External";
const string SPLIT_FLOW =		"SplitFlow";
const string CSPEC = 	    	    	"Cspec";

const string DATA_FLOW = 		"DataFlow";
const string CONTROL_FLOW = 		"ControlFlow";

/* Object types */
const string FLOW_ANCHOR = 		"FlowAnchor";

