location of train ::= integer
location of train ::= *Precision 75%location of train ::= *Units Km*
within limit ::= boolean
within limit ::= *Precision 100 %within limit ::= *Units -*
done ::= boolean
done ::= *Precision 100 %done ::= *Units N/A*
green signal ::= boolean
green signal ::= *Precision 100 %green signal ::= *Units N/A*
red signal ::= boolean
red signal ::= *Precision 100 %red signal ::= *Units N/A*
delay ::= boolean
delay ::= *Precision 100 %delay ::= *Units Seconds*
time_2 ::= integer
time_2 ::= *Precision 100%time_2 ::= *Units Seconds*
weight ::= integer
weight ::= *Precision 100%weight ::= *Units Kgs*
num_pulses ::= integer
num_pulses ::= *Precision Perfectnum_pulses ::= *Units Digital*
time_1 ::= integer
time_1 ::= *Precision 100 %time_1 ::= *Units seconds*
total passenger weight ::= integer
total passenger weight ::= *Precision 89%total passenger weight ::= *Units Kgs*
weight of passenger ::= integer
weight of passenger ::= *Precision N/Aweight of passenger ::= *Units Kgs*
speed of train ::= integer
speed of train ::= *Precision N/Aspeed of train ::= *Units N/A*
pulse ::= boolean
pulse ::= *Precision N/Apulse ::= *Units N/A*
time ::= integer
time ::= *Precision N/Atime ::= *Units N/A*
boolean ::= boolean
integer ::= int
