#!/bin/sh

if [ `whoami` != "root" ]
then
    echo 'You need to be root to do this installation.' >&2
    exit 1
fi

if [ -d /opt/softbench ]
then
    Base=/opt/softbench
elif [ -d /usr/softbench ]
then
    Base=/usr/softbench
else
    echo "Softbench does not appear to be installed on this machine."
    exit
fi

echo ' '
echo Moving new softinit commands ...

if [ ! -f ${Base}/config/softinitsrc/local-override/localinit.orig ]
then
    if [ -f ${Base}/config/softinitsrc/local-override/localinit ]
    then
	cp ${Base}/config/softinitsrc/local-override/localinit ${Base}/config/softinitsrc/local-override/localinit.orig
    fi
else
    cp ${Base}/config/softinitsrc/local-override/localinit.orig ${Base}/config/softinitsrc/local-override/localinit
fi

cat softinitsrc >> ${Base}/config/softinitsrc/local-override/localinit

echo 'Moving types files ...'

cp newtypes ${Base}/config/softtypes/config/C/StP

echo 'Moving menus files...'

#
echo '  Softdm ...'
#

if [ ! -d ${Base}/menus/Softdm/ACTIONS/StP ]
then
  mkdir ${Base}/menus/Softdm/ACTIONS/StP
fi

cp Softdm/ACTIONS/StP/C ${Base}/menus/Softdm/ACTIONS/StP
cp Softdm/ACTIONS/StP/MDF.m ${Base}/menus/Softdm/ACTIONS/StP

#
echo '  Softedit ...'
#

if [ ! -d ${Base}/menus/Softedit/StP ]
then
  mkdir ${Base}/menus/Softedit/StP
fi

if [ ! -d ${Base}/menus/Softedit/StP/Softedit ]
then
  mkdir ${Base}/menus/Softedit/StP/Softedit
fi

cp Softedit/StP/Softedit/C ${Base}/menus/Softedit/StP/Softedit
cp Softedit/StP/Softedit/MDF.m ${Base}/menus/Softedit/StP/Softedit

#
echo '  Static ...'
#

if [ ! -d ${Base}/menus/Static/StP ]
then
  mkdir ${Base}/menus/Static/StP
fi

if [ ! -d ${Base}/menus/Static/StP/Static ]
then
  mkdir ${Base}/menus/Static/StP/Static
fi

cp Static/StP/Static/C ${Base}/menus/Static/StP/Static
cp Static/StP/Static/MDF.m ${Base}/menus/Static/StP/Static

#
# Done with menus
#

echo 'Merging init...'

if [ -s ${Base}/etc/merge-init ]
then
    if grep 'NOTE.*obsoleted' ${Base}/etc/merge-init 2>&1 > /dev/null
    then
	true 
    else
	${Base}/etc/merge-init
    fi
fi

echo 'Merging types...'

${Base}/etc/merge-types

echo ' '
echo 'Done.'
