//*****************************************************************************
// DESCRIPTION: UML_Include_D.inc
//              ----------------------
//              (c) 1997 by AONIX GmbH
//*****************************************************************************
//
// Include Statements for all included files needed for the german UML-Report. 
// This is the only file included in the UML_Report_D wrapper and allows us
// to change our include strategy in future versions of the report
//*****************************************************************************
// Included Files:
// 
// UML_Include.inc :     Includes all other files, needed for UML_Report
// UML_Externals_D.inc : Includes german externals + mapping for UML_Report_D
//*****************************************************************************
#include "qrl/include/UML_Include.inc"
#include "qrl/include/UML_Externals_D.inc"

