//*****************************************************************************
// DESCRIPTION: UML_Include_F.inc
//              ----------------------
//              (c) 1997 by AONIX GmbH
//*****************************************************************************
//
// Include Statements for all included files needed for the french UML-Report. 
// This is the only file included in the UML_Report_F wrapper and allows us
// to change our include strategy in future versions of the report
//*****************************************************************************
// Included Files:
// 
// UML_Include.inc :     Includes all other files, needed for UML_Report
// UML_Externals_F.inc : Includes french externals + mapping for UML_Report_F
//*****************************************************************************
#include "qrl/include/UML_Include.inc"
#include "qrl/include/UML_Externals_F.inc"

