////////////////////////////////////////////////////////////////////////////////
//
// 	sccsid[] = %W% %Y% %D%
// 	StP/Core
// 	Confidential property of Interactive Development Environments, Inc.
// 	Copyright (c) 1992-1995
// 	All rights reserved
//
////////////////////////////////////////////////////////////////////////////////

const string  	NGOAE_CLASS = "ngoae";		// non-graphical oae
const string  	OAE_CLASS = "oae";		// non-graphical oae

const int	CH_ANY = 0;			// send to all connections
const int	CH_FIRST = -1;			// send to first
const int	CH_SELF = -2;			// send to self

const string	OAE_CMD_ANNOT_EDIT = "AnnotEdit ";
const string	OAE_CMD_ANNOT_UNLOAD = "AnnotUnload";
const string	OAE_CMD_NOTE_SEL = "NoteSelect ";
const string	OAE_CMD_NOTE_ADD = "NoteAdd ";
const string	OAE_CMD_ITEM_SEL = "ItemSelect ";
const string	OAE_CMD_ITEM_DEL = "EditorDelete";
const string	OAE_CMD_ITEM_ADD = "ItemAdd ";
const string	OAE_CMD_ITEM_SETVAL = "EditorSetValue ";
const string	OAE_CMD_ITEM_ADVAL = "ItemAdvanceValue";
const string	OAE_CMD_FILE_SAVE = "FileSave";

