//
//      sccsid[] = %W% %Y% %D%
//      StP/UML
//      StP Core
//      Confidential property of Interactive Development Environments, Inc.
//      Copyright (c) 1992-1998
//      All rights reserved
//


// definitions to handle the navigations between ObjectAda and StP

const string  CLASS_PACKAGE_NAME_PREFIX           = "";
const string  CLASS_PACKAGE_NAME_SUFFIX           = "";
